services:

###> doctrine/doctrine-bundle ###
  database:
    container_name: "${PROJECT_NAME}_mysql"
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
    - gsbveto
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    depends_on:
      - database
    ports:
      - "8088:80"
      - "8083:443"
    environment:
      PMA_HOST: database
      PMA_PORT: "3306"
    volumes:
      - /sessions
    networks:
    - gsbveto

  php:
    image: ${PROJECT_NAME:-}app-php
    container_name: "${PROJECT_NAME}_php"
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-app}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # The two next lines can be removed after initial installation
      # SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      # STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    networks:
    - gsbveto

networks:
  gsbveto:

volumes:
  caddy_data:
  caddy_config:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###